/*
 * @file init.h
 * @brief Hardware initialization code
 *
 * @author Garrett Knuf
 * @date 4/1/2024
 */

#ifndef INC_INIT_H_
#define INC_INIT_H_


/**
 * @brief System Clock Configuration
 * Auto-generated by CubeIDE.
 */
void SystemClock_Config(void);

/**
 * @brief GPIO Initialization Function
 * Auto-generated by CubeIDE.
 */
void MX_GPIO_Init(void);

/**
 * @brief USART2 Initialization Function
 * Auto-generated by CubeIDE.
 */
void MX_USART2_UART_Init(void);

/**
 * @brief SPI2 Initialization Function
 * Auto-generated by CubeIDE.
 */
void MX_SPI2_Init(void);


#endif /* INC_INIT_H_ */
